### PR TITLE
test: wallet-level swap test (WIP)

### PR DESCRIPTION
**Pull request by dckc**
- [x] migrate from `agoric install` to `yarn` for dependencies
 - [x] wallet test a la [How do test off\-chain client interaction without a full running chain? · #8683](https://github.com/Agoric/agoric-sdk/discussions/8683)
 - [x] update chain deployment scripts from dapp-offer-up

### CODE REVIEW

**Comment by dckc** [comment]
## migrated from `agoric install` to just `yarn`

With `agoric install`, dependencies are messed up or something:

~/projects/dapp-swaparoo/contract
16:17 connolly@bldbox$ LOCKDOWN_OPTIONS='{"errorTaming":"unsafe","stackFiltering":"verbose"}' yarn test test/test-swap-wallet.js yarn run v1.22.19
warning package.json: No license field
$ ava --verbose test/test-swap-wallet.js

'@endo/lockdown' sniffed and found a 'LOCKDOWN_OPTIONS' environment variable

  Uncaught exception in test/test-swap-wallet.js

  AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The expression evaluated to a falsy value:

    assert(refs.runnerChain)

    at Object.<anonymous> (/home/connolly/projects/agoric-sdk/node_modules/ava/lib/worker/main.cjs:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at extensions.<computed> [as .js] (file:///home/connolly/projects/dapp-swaparoo/node_modules/ava/lib/worker/dependency-tracker.js:42:5)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

SES_UNHANDLED_REJECTION: (AssertionError#1)
  ✘ test/test-swap-wallet.js exited with a non-zero exit code: 1
  ─

  1 uncaught exception
error Command failed with exit code 1.

**Comment by dckc** [comment]
## patched @agoric/vats to include index.js

you may have to `npx patch-package` after you `yarn`.
There's a conventional way to automate that, but I'm not facile with it yet.

**Comment by dckc** [comment]
## working: bootstrap and start contract under ava

```
$ yarn test test/test-swap-wallet.js 
yarn run v1.22.19
$ ava --verbose test/test-swap-wallet.js

start-contract-proposal.js module evaluating
issuer IST: new Promise
brand IST: new Promise
issuer IST settled; remaining: []
brand IST settled; remaining: []
bundles/ bundle-swaparoo.js valid: 563 files bundled at 2023-12-23T23:41:42.296Z with size 4502113
installContract() ... swaparoo
startContract()...
  ✔ bootstrap and start contract (642ms)
    ℹ bootstrap
    ℹ publish bundle b1-97d1a
    ℹ install contract
    ℹ start contract
    ℹ Object @Alleged: InstanceHandle {}
installation swaparoo: new Promise
swaparoo (re)installed
installation swaparoo settled; remaining: []
CoreEval script: started game contract Object [Alleged: InstanceHandle] {}
CoreEval script: share via agoricNames: none
instance swaparoo: new Promise
swaparoo (re)installed
instance swaparoo settled; remaining: []
  ─

  1 test passed
Done in 1.36s.
```

**Comment by dckc** [comment]
## can't deploy the bundle now. it's too big.

I got a version of the basic swap test working with the bootstrap stuff above. I tried deploying it to a chain, but it's too big.

```
+ agd tx swingset install-bundle --compress @/root/.agoric/cache/b1-a3f08fc2ee57ec9a653a8f283ddcd15f0b8f6983190b9cf4ee677320435062b0e12b7292e467e2c409da4afdbf18f0938912c615a2f459f717e38fdc414cce97.json --from user1 --keyring-backend=test --gas=auto --chain-id=agoriclocal -bblock --yes -o json
Error: RPC error -32600 - Invalid Request: error reading request body: http: request body too large
```

4.3M Dec 24 01:24 bundle-contract.js

looks like

 - https://github.com/Agoric/agoric-sdk/issues/8621

current status:

2023-12-23 19:37 3058952 build: yarn start:contract
2023-12-23 19:26 c570d25 chore: update chain deployment scripts
2023-12-23 19:04 cd1d694 test: basic swap wallet test (WIP)
2023-12-23 18:51 15da241 test: update mintStable from dapp-offer-up
2023-12-23 18:51 62a0336 fix(swaparoo): respect feeAmount term in feeShape
2023-12-23 18:51 8ffa3b6 style(swaparoo): organize imports
2023-12-23 16:19 0d65f46 test: toward wallet test: bootstrap and start contract

**Comment by dckc** [comment]
## wallet level basic swap test working

2023-12-24 00:07 3e0c7e7 test: factor out mockWalletFactory

```
~/projects/dapp-swaparoo/contract
00:05 connolly@bldbox$ yarn test test/test-swap-wallet.js 
yarn run v1.22.19
$ ava --verbose test/test-swap-wallet.js

start-contract-proposal.js module evaluating
issuer IST: new Promise
brand IST: new Promise
issuer BLD: new Promise
brand BLD: new Promise
issuer IST settled; remaining: [ 'BLD' ]
brand IST settled; remaining: [ 'BLD' ]
issuer BLD settled; remaining: []
brand BLD settled; remaining: []
bundles/ bundle-swaparoo.js valid: 563 files bundled at 2023-12-24T05:14:19.419Z with size 4502113
installContract() ... swaparoo
startContract()...
  ✔ bootstrap and start contract (649ms)
    ℹ bootstrap
    ℹ publish bundle b1-a3f08
    ℹ install contract
    ℹ start contract
    ℹ Object @Alleged: InstanceHandle {}
installation swaparoo: new Promise
swaparoo (re)installed
installation swaparoo settled; remaining: []
CoreEval script: started game contract Object [Alleged: InstanceHandle] {}
CoreEval script: share via agoricNames: none
instance swaparoo: new Promise
swaparoo (re)installed
instance swaparoo settled; remaining: []
bundles/ bundle-centralSupply.js valid: 414 files bundled at 2023-12-24T05:18:02.599Z with size 3226621
@@TODO: check invitation amount against instance {
  brand: Object [Alleged: Zoe Invitation brand] {},
  value: [
    {
      customDetails: [Object],
      description: 'matchOffer',
      handle: Object [Alleged: InvitationHandle] {},
      installation: Object [Alleged: BundleIDInstallation] {},
      instance: Object [Alleged: InstanceHandle] {}
    }
  ]
}
  ✔ basic swap (1.3s)
    ℹ jack got {
        Cow: {
          brand: Object @Alleged: BLD brand {},
          value: 0n,
        },
        MagicBeans: {
          brand: Object @Alleged: ZDEFAULT brand {},
          value: 5n,
        },
      }
    ℹ alice got {
        Cow: {
          brand: Object @Alleged: BLD brand {},
          value: 10n,
        },
        Fee: {
          brand: Object @Alleged: ZDEFAULT brand {},
          value: 0n,
        },
        MagicBeans: {
          brand: Object @Alleged: ZDEFAULT brand {},
          value: 0n,
        },
      }
  ─

  2 tests passed
Done in 2.67s.
```

**Review by dtribble — APPROVED** [review]

**Pull request merged**
